[project]
name = "alexandria"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "accelerate>=1.6.0",
    "datasets>=3.5.1",
    "evaluate>=0.4.3",
    "timm>=1.0.15",
    "torch>=2.7.0",
    "transformers>=4.51.3",
]
