services:
  vllm-server:
    image: vllm/vllm-openai:latest
    runtime: nvidia
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "8000:8000"
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HF_TOKEN}
    command: ["--model", "${MODEL}", "--host", "0.0.0.0", "--port", "8000"]
  
  embeddings-server:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.7
    ipc: host
    ports:
      - "8080:80"
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HF_TOKEN}
      - MODEL_ID=${EMBEDDINGS_MODEL}
      - DEVICE=cpu

  db:
    image: pgvector/pgvector:pg17
    restart: always
    ports:
      - 5432:5432
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - .data:/var/lib/pohstgresql/data